######################################################################
# Automatically generated by qmake (2.01a) Sat Jun 22 22:07:54 2013
######################################################################

#TEMPLATE = app
TARGET = edowser
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += edowser.h
SOURCES += edowser.cpp

include(../qt-solutions/qtbrowserplugin/src/qtbrowserplugin.pri)
 
 
